import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import Note from "@/components/Note";
import "./globals.css";
import Menu from "@/components/Menu";
import { Toaster } from "@/components/ui/toaster";

export const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
});

export const metadata: Metadata = {
    title: "Curata",
    description: "Generated by create next app",
    icons: {
        icon: "https://cognimate.vercel.app/favicon.svg",
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={cn(
                    "relative font-sans antialiased",
                    fontSans.variable
                )}
            >
                <Menu />
                {children}
                <Note />
                <Toaster />
            </body>
        </html>
    );
}
